### Numpy  Array and basics 
Learn about numpy with Umar Pathan

In [3]:
import numpy as np 

In [4]:
arr_1d = np.array([1,2,3,4,5])
print("1D array: ", arr_1d)

1D array:  [1 2 3 4 5]


In [6]:
arr_2d = np.array([[1,2,3],[4,5,6]])
print("2D array: ", arr_2d)

2D array:  [[1 2 3]
 [4 5 6]]


### List vs Numpy array

In [7]:
py_list = [1,2,3]
print("Python list multi..", py_list * 3)

Python list multi.. [1, 2, 3, 1, 2, 3, 1, 2, 3]


In [9]:
np_array = np.array([1,2,3]) # elements wise mutliplication...
print("Python list multi..", np_array * 3)


Python list multi.. [3 6 9]


In [11]:
import time
start = time.time()
py_list = [i * 2 for i in range(1000000)]
print("\n List operation time: ", time.time()-start)


start = time.time()
np_array = np.arange(1000000) 
print("\n Numpy operation time: ", time.time()-start)


 List operation time:  0.09232044219970703

 Numpy operation time:  0.002771615982055664


### Creating array from scratch 

In [15]:
zeros = np.zeros((3,4))
print("zeros array: \n", zeros)

zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [17]:
ones = np.ones((3,3))
print("ones array: \n", ones)

ones array: 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [20]:
full = np.full((2,2), 9)
print("full array: \n", full)

full array: 
 [[9 9]
 [9 9]]


In [22]:
random = np.random.random((2,3))
print("random array: \n", random)

random array: 
 [[0.121762   0.22859001 0.08261419]
 [0.650143   0.70417076 0.48982539]]


In [23]:
sequence = np.arange(0,10,3)
print("sequence array: \n", sequence)

sequence array: 
 [0 3 6 9]


In [25]:
sequence = np.arange(0,10,1)
print("sequence array: \n", sequence)

sequence = np.arange(0,10,4)
print("sequence array: \n", sequence)

sequence array: 
 [0 1 2 3 4 5 6 7 8 9]
sequence array: 
 [0 4 8]


### Vector, Matrix and Tensor


In [29]:
vector = np.array([1,2,3])
print("vector:", vector)


matrix = np.array([[1,2,3],
                   [4,5,6,]])
print("Matrix:", matrix)

tensor = np.array([[
                   [1,2],[3,4]],
                   [[5,6], [7,8]
                          ]])
print("tensor:", tensor)

vector: [1 2 3]
Matrix: [[1 2 3]
 [4 5 6]]
tensor: [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array Properties

In [30]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print("Shape ", arr.shape)
print("Dimension ", arr.ndim)
print("Size ", arr.size)
print("DType ", arr.dtype)

Shape  (2, 3)
Dimension  2
Size  6
DType  int64


### Array Reshaping

In [40]:
arr = np.arange(12)
print("Array:", arr)

reshaped = arr.reshape((4,3))
print("\n Reshaped Array: \n",reshaped)

flattend = reshaped.flatten()
print("\n Flattend Array:", flattend)

# ravel (returns the view, instead of copy)
raveled = reshaped.ravel()
print("\n Raveled Array:", raveled)


Array: [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Reshaped Array: 
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

 Flattend Array: [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Raveled Array: [ 0  1  2  3  4  5  6  7  8  9 10 11]


### Transpose 

In [42]:
transpose = reshaped.T
print("\n Transposed Array: ", transpose)


 Transposed Array:  [[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]
