### Numpy Array Operations

In [1]:
import numpy as np

In [11]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("Basic Slicing :" ,arr[2:7])
print("With Step :" ,arr[1:8:3])
print("Negative Indexing :" ,arr[-5])

Basic Slicing : [3 4 5 6 7]
With Step : [2 5 8]
Negative Indexing : 6


In [12]:
# reshape the existing 1D array `arr` into 2D arrays

# reshape to 2 rows x 5 columns
arr_2d = arr.reshape(2, 5)
print("2x5 array:\n", arr_2d)

# alternative: 5 rows x 2 columns
arr_2d_alt = arr.reshape(5, 2)
print("5x2 array:\n", arr_2d_alt)

# column and row views
arr_col = arr[:, None]   # shape (10,1)
arr_row = arr[None, :]   # shape (1,10)
print("Column shape:", arr_col.shape)
print("Row shape:", arr_row.shape)

2x5 array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
5x2 array:
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
Column shape: (10, 1)
Row shape: (1, 10)


In [15]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print("Specific Element:", arr_2d[1,2])
print("Entire row:", arr_2d[1])
print("Entire row:", arr_2d[:,2])

Specific Element: 6
Entire row: [4 5 6]
Entire row: [3 6 9]


### Sorting 


In [53]:
unsorted = np.array([3, 1, 4, 1, 5, 9, 2, 6, 3])
print("Sorted Array:" , np.sort(unsorted))


arr_2d_unsorted = np.array([[3, 1,],[1, 2,],[2, 3,]])
print("Sorted 2D Array by Column:" , np.sort(arr_2d_unsorted, axis=0))

Sorted Array: [1 1 2 3 3 4 5 6 9]
Sorted 2D Array by Column: [[1 1]
 [2 2]
 [3 3]]


### Filter 

In [ ]:
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
even_number = numbers [numbers % 2 == 0]
print("Even numbers", even_number)

Even numbers [ 2  4  6  8 10]


### Filter with mask

In [25]:
mask = numbers > 5
print("Numbers greater than 5",numbers[mask])

Numbers greater than 5 [ 6  7  8  9 10]


### Fancy indexing vs np.where()

In [28]:
indices = [0, 2, 5]
print(numbers[indices])

# with where 
where_result = np.where(numbers > 5)
print(where_result)
print("NP where", numbers[where_result])

[1 3 6]
(array([5, 6, 7, 8, 9]),)
NP where [ 6  7  8  9 10]


In [33]:
condition_array = np.where(numbers > 5,numbers*1, numbers)
print(condition_array)

[ 1  2  3  4  5  6  7  8  9 10]


### Adding and removing data

In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

#combined = arr1 + arr2
combined = np.concatenate((arr1,arr2))
print(combined)

[1 2 3 4 5 6]


### Array compatibilty

In [43]:
a = np.array ([1, 2, 3])
b = np.array ([4, 5, 6, 7])
c = np.array ([7, 8, 9])


print("Compatibilty shapes" , a.shape == b.shape)
print("Compatibilty shapes" , b.shape == c.shape)
print("Compatibilty shapes" , c.shape == a.shape)

Compatibilty shapes False
Compatibilty shapes False
Compatibilty shapes True


In [50]:
original = np.array([[1,2],[3,4]])
new_row = np.array([5,6])

with_new_row = np.vstack((original, new_row))
print(original)
print(with_new_row)

new_col = np.array([[7],[8]])
with_new_col = np.hstack((original, new_col))
print(original)
print(with_new_col)


[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]]
[[1 2 7]
 [3 4 8]]


In [52]:
arr = np.array([1, 2, 3, 4, 5])
deleted = np.delete(arr, 3)
print("Array after deletion:",deleted)

Array after deletion: [1 2 3 5]
